services:
- type: web
  name: onegrab-fe
  runtime: static
  repo: https://github.com/sai43/onegrab-fe
  buildCommand: vite build
  staticPublishPath: dist
  domains:
  - onegrab.in
  - www.onegrab.in
  routes:
  - type: redirect
    source: /*
    destination: /index.html
  autoDeployTrigger: commit
version: "1"
